export default [
    {
        id: '1',
        title: 'Dolly Laranja',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '10.50',
        img: require('../../../assets/bebidas/r1.jpg'),
        icon: 'plus',
        p: '5.45',
        m: '7.00',
        g: '10.50',
        type:'listDrinkMenu'
    },
    {
        id: '2',
        title: 'Dolly Limão',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '20.50',
        img: require('../../../assets/bebidas/r2.jpg'),
        icon: 'plus',
        p: '8.45',
        m: '17.00',
        g: '20.50',
        type:'listDrinkMenu'
    },
    {
        id: '3',
        title: 'Chicken Tikka',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '30.50',
        img: require('../../../assets/bebidas/r3.jpg'),
        icon: 'plus',
        p: '10.45',
        m: '27.00',
        g: '30.50',
        type:'listDrinkMenu'
    },
    {
        id: '4',
        title: 'Vodka',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '40.50',
        img: require('../../../assets/bebidas/r4.jpg'),
        icon: 'plus',
        p: '15.45',
        m: '37.00',
        g: '40.50',
        type:'listDrinkMenu'
    },
    {
        id: '5',
        title: 'Drink ligth',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '50.50',
        img: require('../../../assets/bebidas/r5.jpg'),
        icon: 'plus',
        p: '34.45',
        m: '44.00',
        g: '50.50',
        type:'listDrinkMenu'
    },
    {
        id: '6',
        title: 'Guarana',
        description: 'Tomate | Grillet Mushroom | jlapeno',
        value: '60.50',
        img: require('../../../assets/bebidas/r6.jpg'),
        icon: 'plus',
        p: '26.45',
        m: '52.00',
        g: '60.50',
        type:'listDrinkMenu'
    },
    {
        id: '7',
        title: 'Bolo de chocolate branco',
        description: 'Tomate | Grillet  | jlapeno',
        value: '96.50',
        img: require('../../../assets/bolos/b1.jpg'),
        icon: 'plus',
        p: '50.45',
        m: '77.00',
        g: '96.50',
        type: 'listCakeMenu'
    },
    {
        id: '8',
        title: 'Bolo de morango',
        description: 'Tomate |  Mushroom | jlapeno',
        value: '126.50',
        img: require('../../../assets/bolos/b2.jpg'),
        icon: 'plus',
        p: '79.90',
        m: '100.00',
        g: '126.50',
        type: 'listCakeMenu'
    },
    {
        id: '9',
        title: 'Bolo de chocolate',
        description: 'Tomate | Grillet Mushroom ',
        value: '110.50',
        img: require('../../../assets/bolos/b3.jpg'),
        icon: 'plus',
        p: '56.45',
        m: '88.99',
        g: '110.50',
        type: 'listCakeMenu'
    },
    {
        id: '10',
        title: 'Bolo de brigadeiro',
        description: 'Grillet Mushroom | jlapeno',
        value: '142.50',
        img: require('../../../assets/bolos/b4.jpg'),
        icon: 'plus',
        p: '115.45',
        m: '133.40',
        g: '142.50',
        type: 'listCakeMenu'
    },
    {
        id: '11',
        title: 'Bolo recheado',
        description: 'Tomate | Grillet Mushroom',
        value: '130.50',
        img: require('../../../assets/bolos/b5.jpg'),
        icon: 'plus',
        p: '95.45',
        m: '112.00',
        g: '130.50',
        type: 'listCakeMenu'
    },
    {
        id: '12',
        title: 'Bolo misto',
        description: 'Tomate | Mushroom | jlapeno',
        value: '135.50',
        img: require('../../../assets/bolos/b6.jpg'),
        icon: 'plus',
        p: '96.35',
        m: '122.00',
        g: '135.50',
        type: 'listCakeMenu'
    },
    {
        id: '13',
        title: 'Brigadeiro',
        description: 'Tomate | Grillet  | jlapeno',
        value: '96.50',
        img: require('../../../assets/doces/d1.jpg'),
        icon: 'plus',
        p:'53.45',
        m:'72.00',
        g:'96.50',
        type:'listSweetMenu'
    },
    {
        id: '14',
        title: 'Bolacha de mel',
        description: 'Tomate |  Mushroom | jlapeno',
        value: '126.50',
        img: require('../../../assets/doces/d2.jpg'),
        icon: 'plus',
        p:'100.45',
        m:'117.00',
        g:'126.50',
        type:'listSweetMenu'
    },
    {
        id: '15',
        title: 'Pão de mel',
        description: 'Tomate | Grillet Mushroom ',
        value: '110.50',
        img: require('../../../assets/doces/d3.jpg'),
        icon: 'plus',
        p:'75.45',
        m:'88.00',
        g:'110.50',
        type:'listSweetMenu'
    },
    {
        id: '16',
        title: 'Pudin',
        description: 'Grillet Mushroom | jlapeno',
        value: '142.50',
        img: require('../../../assets/doces/d4.jpg'),
        icon: 'plus',
        p:'115.45',
        m:'127.00',
        g:'142.50',
        type:'listSweetMenu'
    },
    {
        id: '17',
        title: 'Brigadeiro recheado misto',
        description: 'Tomate | Grillet Mushroom',
        value: '130.50',
        img: require('../../../assets/doces/d5.jpg'),
        icon: 'plus',
        p:'65.45',
        m:'113.00',
        g:'130.50',
        type:'listSweetMenu'
    },
    {
        id: '18',
        title: 'Doce de coco',
        description: 'Tomate | Mushroom | jlapeno',
        value: '135.50',
        img: require('../../../assets/doces/d6.jpg'),
        icon: 'plus',
        p:'112.45',
        m:'117.00',
        g:'135.50',
        type:'listSweetMenu'
    },
    {
        id: '19',
        title: 'Variados',
        description: 'Tomate | Mushroom | jlapeno',
        value: '135.50',
        img: require('../../../assets/doces/d7.jpg'),
        icon: 'plus',
        p:'48.45',
        m:'116.00',
        g:'135.50',
        type:'listSweetMenu'
    },
    {
        id: '20',
        title: 'Misto',
        description: 'Tomate | Mushroom | jlapeno',
        value: '135.50',
        img: require('../../../assets/doces/d8.jpg'),
        icon: 'plus',
        p:'77.45',
        m:'121.55',
        g:'135.50',
        type:'listSweetMenu'
    },
    {
        id: '21',
        title: 'X salada',
        description: 'Tomate | Grillet  | jlapeno',
        value: '10.50',
         img: require('../../../assets/lanches/s1.jpg'),
        icon: 'plus',
        p:'5.45',
        m:'7.00',
        g:'10.50',
        type:'listLunchMenu'
    },
    {
        id: '22',
        title: 'Pão recheado',
        description: 'Tomate |  Mushroom | jlapeno',
        value: '20.50',
         img: require('../../../assets/lanches/s2.jpg'),
        icon: 'plus',
        p:'6.45',
        m:'17.00',
        g:'20.50',
        type:'listLunchMenu'
    },
    {
        id: '23',
        title: 'Pão de forma',
        description: 'Tomate | Grillet Mushroom ',
        value: '30.50',
         img: require('../../../assets/lanches/s3.jpg'),
        icon: 'plus',
        p:'16.45',
        m:'25.00',
        g:'30.50',
        type:'listLunchMenu'
    },
    {
        id: '24',
        title: 'Coxinhas',
        description: 'Grillet Mushroom | jlapeno',
        value: '40.50',
         img: require('../../../assets/lanches/s4.jpg'),
        icon: 'plus',
        p:'25.45',
        m:'37.00',
        g:'40.50',
        type:'listLunchMenu'
    },
    {
        id: '25',
        title: 'Hamburger',
        description: 'Tomate | Grillet Mushroom',
        value: '50.50',
         img: require('../../../assets/lanches/s5.jpg'),
        icon: 'plus',
        p:'25.45',
        m:'37.00',
        g:'50.50',
        type:'listLunchMenu'
    },
    {
        id: '26',
        title: 'Kit lanche',
        description: 'Tomate | Mushroom | jlapeno',
        value: '60.50',
         img: require('../../../assets/lanches/s6.jpg'),
        icon: 'plus',
        p:'45.45',
        m:'55.00',
        g:'60.50',
        type:'listLunchMenu'
    },
    {
        id: '27',
        title: 'Pizza mussarela',
        description: 'Tomate | Grillet  | jlapeno',
        value: '46.50',
        img: require('../../../assets/pizzas/p1.jpg'),
        icon: 'plus',
        p: '35.45',
        m: '40.00',
        g: '46.50',
        type:'listPizzaMenu'
    },
    {
        id: '28',
        title: 'Pizza calabresa',
        description: 'Tomate |  Mushroom | jlapeno',
        value: '26.50',
        img: require('../../../assets/pizzas/p2.jpg'),
        icon: 'plus',
        p: '15.45',
        m: '22.00',
        g: '26.50',
        type:'listPizzaMenu'
    },
    {
        id: '29',
        title: 'Pizza apimentada',
        description: 'Tomate | Grillet Mushroom ',
        value: '37.50',
        img: require('../../../assets/pizzas/p3.jpg'),
        icon: 'plus',
        p: '22.45',
        m: '27.00',
        g: '37.50',
        type:'listPizzaMenu'
    },
    {
        id: '30',
        title: 'Pizza de alho',
        description: 'Grillet Mushroom | jlapeno',
        value: '42.50',
        img: require('../../../assets/pizzas/p4.jpg'),
        icon: 'plus',
        p: '33.45',
        m: '39.00',
        g: '42.50',
        type:'listPizzaMenu'
    },
    {
        id: '31',
        title: 'Torta de pizza',
        description: 'Tomate | Grillet Mushroom',
        value: '40.50',
        img: require('../../../assets/pizzas/p5.jpg'),
        icon: 'plus',
        p: '26.45',
        m: '31.00',
        g: '40.50',
        type:'listPizzaMenu'
    },
    {
        id: '32',
        title: 'Pizza portuguesa',
        description: 'Tomate | Grillet Mushroom',
        value: '35.50',
        img: require('../../../assets/pizzas/p6.jpg'),
        icon: 'plus',
        p: '12.45',
        m: '27.00',
        g: '35.50',
        type:'listPizzaMenu'
    },
]
